// hard coded data

movies = [{
    title: 'Jaws',
    year: 1975,
    director: 'Stephen Spielberg',
    kills: 6
},
{
    title: 'Alien',
    year: 1979,
    director: 'Ridley Scott',
    kills: 6
},
{
    title: 'Nightmare on Elm Street',
    year: 1975,
    director: 'Roberrt Shaye',
    kills: 4
},
{
    title: 'Halloween',
    year: 1978,
    director: 'John Carpenter',
    kills: 5
},]

victims = [
    {
        name: "Judith Meyers",
        age: ,
        cause_of_death: "Stabbed 9x with Butcher knife",
        movie: "Halloween",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: 'Mechanic dude',
        age: ,
        cause_of_death: "Body seen in grass",
        movie: "Halloween",
        golden_chainsaw: false,
        dull_machete: true,
    },
    {
        name: "Annie Brackett",
        age: ,
        cause_of_death: "Strangled and throat slit",
        movie: "Halloween",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Bob Simms",
        age: ,
        cause_of_death: "Stabbed through chest",
        movie: "Halloween",
        golden_chainsaw: true,
        dull_machete: false,
    },
    {
        name: "Lynda",
        age: ,
        cause_of_death: "Strangled by phone cord",
        movie: "Halloween",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Kane",
        age: ,
        cause_of_death: "Chest bursted by alien",
        movie: "Alien",
        golden_chainsaw: true,
        dull_machete: false,
    },
    {
        name: "Brett",
        age: ,
        cause_of_death: "Impaled through head with second mouth",
        movie: "Alien",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Dallas",
        age: ,
        cause_of_death: "Killed offscreen",
        movie: "Alien",
        golden_chainsaw: false,
        dull_machete: true,
    },
    {
        name: "Ash (Android)",
        age: ,
        cause_of_death: "Decapitated and dismantled",
        movie: "Alien",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Parker",
        age: ,
        cause_of_death: "Impaled by alien's second mouth",
        movie: "Alien",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Lambert",
        age: ,
        cause_of_death: "Killed offscreen",
        movie: "Alien",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Tina Grey",
        age: ,
        cause_of_death: "Finger knifed in the chest",
        movie: "The Nightmare on Elm Street",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Rod Lane",
        age: ,
        cause_of_death: "Hanged in jail cell",
        movie: "The Nightmare on Elm Street",
        golden_chainsaw: false,
        dull_machete: true,
    },
    {
        name: "Glen Lantz",
        age: ,
        cause_of_death: "Pulled into bed and turned into blood geyser",
        movie: "The Nightmare on Elm Street",
        golden_chainsaw: true,
        dull_machete: false,
    },
    {
        name: "Marge Thompson",
        age: ,
        cause_of_death: "Burned to death",
        movie: "The Nightmare on Elm Street",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Chrissie Watkins",
        age: ,
        cause_of_death: "Eaten bu Bruce",
        movie: "Jaws",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Alex Kinter",
        age: ,
        cause_of_death: "Eaten",
        movie: "Halloween",
        golden_chainsaw: false,
        dull_machete: true,
    },
    {
        name: "Ben Gardner",
        age: ,
        cause_of_death: "Found dead in boat",
        movie: "Jaws",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Man in Estuary",
        age: ,
        cause_of_death: "Eaten",
        movie: "Jaws",
        golden_chainsaw: false,
        dull_machete: false,
    },
    {
        name: "Quint",
        age: ,
        cause_of_death: "Falls and gets eaten",
        movie: "Jaws",
        golden_chainsaw: true,
        dull_machete: false,
    },
    {
        name: "Bruce the Shark",
        age: ,
        cause_of_death: "Blown up by shooting oxygen tank in mouth",
        movie: "Jaws",
        golden_chainsaw: false,
        dull_machete: false,
    },
]
